<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>BetterFlyCam</AssemblyName>
    <RootNamespace>BetterFlyCam</RootNamespace>
    <LangVersion>latest</LangVersion>

    <GamePath>D:\A Township Tale</GamePath>
 
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>$(GamePath)\MelonLoader\net35\MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(GamePath)\MelonLoader\net35\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Alta.Api.Client">
      <HintPath>$(GamePath)\A Township Tale_Data\Managed\Alta.Api.Client.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Alta.Api.DataTransferModels">
      <HintPath>$(GamePath)\A Township Tale_Data\Managed\Alta.Api.DataTransferModels.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Alta.EventBus.Runtime">
      <HintPath>$(GamePath)\A Township Tale_Data\Managed\Alta.EventBus.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Root.Township">
      <HintPath>..\..\..\A Township Tale\A Township Tale_Data\Managed\Root.Township.dll</HintPath>
    </Reference>
	<Reference Include="UnityEngine.JSONSerializeModule">
		<HintPath>$(GamePath)\A Township Tale_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath>
		<Private>false</Private>
	</Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GamePath)\A Township Tale_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(GamePath)\A Township Tale_Data\Managed\Unity.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
	<Reference Include="UnityEngine.TextRenderingModule">
		<HintPath>$(GamePath)\A Township Tale_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
		<Private>false</Private>
	</Reference>
	<Reference Include="UnityEngine.PhysicsModule">
		<HintPath>$(GamePath)\A Township Tale_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
		<Private>false</Private>
	</Reference>
  </ItemGroup>

  <Target Name="CopyToMods" AfterTargets="Build">
    <Copy SourceFiles="$(TargetDir)$(AssemblyName).dll" DestinationFolder="$(GamePath)\Mods\" SkipUnchangedFiles="false" />
  </Target>

</Project>
